### ISSUE TITLE
报错：(Session info: chrome=96.0.4664.110)

### ISSUE THREAD

**Issue by tansen87** [Levitans/XueXiTongBrushClass#3]
![Uploading image.png…]()
你好 我想请问一下我的报错问题
下面是报错内容：
Traceback (most recent call last):
  File "D:\study\brush\main.py", line 57, in <module>
    coursesList = xueXiTong.getCourses()
  File "D:\study\brush\package\ControlWeb\xueXiTong.py", line 44, in getCourses
    self.course.getCourseObjectAndName(self.__driver)
  File "D:\study\brush\package\ControlWeb\course.py", line 19, in getCourseObjectAndName
    driver.find_element(By.CLASS_NAME, "zne_kc_icon").click()
  File "D:\Software\python3.9\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Software\python3.9\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Software\python3.9\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".zne_kc_icon"}
  (Session info: chrome=96.0.4664.110)

**Comment by Levitans** [comment]
仓库里的我好久没更新了，最新的在我本地还没上传，你等几天在看看
